### PR TITLE
fix implicitly nullable via default value null for PHP-8.4

### PR DESCRIPTION
**Pull request by txdFabio**
use of explicit nullable type for php-8.4 compatibility

### CODE REVIEW

**Comment by itsgoingd** [comment]
Thanks!

**Comment by txdFabio** [comment]
any idea on when it will be included in a tagged release?

**Comment by itsgoingd** [comment]
Hey, I will try to do it this weekend, sorry for the wait.

**Comment by itsgoingd** [comment]
Included in Clockwork 5.3.3, thanks.

**Pull request merged**
