### PR TITLE
fixes the ability to use other event dispatchers when using clockwork, for example EventFake when testing

### PR DESCRIPTION
**Pull request by robclancy**

### CODE REVIEW

**Comment by itsgoingd** [comment]
Thanks! I'll need to figure out how do I want to handle Laravel 4 compatibility, since this will require Laravel 5+.

**Comment by robclancy** [comment]
You are going to keep getting Laravel 4 vs 5 issues as time goes by. I think either a separate package for 4 or at least separate drivers etc. So a separate `EloquentLaravel4DataSource`

**Comment by itsgoingd** [comment]
Yeah, I’m thinking about dropping Laravel 4 support in Clockwork 2.1 atm. Ideally I would wait for 3.0 but last major version took like 3 years. :)

**Comment by robclancy** [comment]
If you drop support just change the major version to 3. That way you can tell people "stay on version 2 with Laravel 4".

**Comment by itsgoingd** [comment]
Let's do this.

**Comment by robclancy** [comment]
Hopefully I have time to help with this project soon. I have ideas and things that annoy me that I want to fix. Started to see a lot more use from people in the #laravel channel on IRC.

**Pull request merged**
