### PR TITLE
Prefer using $data->__debugInfo() when serializing object

### PR DESCRIPTION
**Pull request by mahagr**
Related to #369.

To trim down the amount of serialized data and make the dump more readable, add support for using `$data->__debugInfo()` when it is available.

This will
* greatly speed up serializer when serializing objects with `__debugInfo()`
* greatly speed up GUI as there is far less data to be downloaded and processed
* greatly improve readability as objects do not have redundant dumped data

### CODE REVIEW

**Comment by itsgoingd** [comment]
Thanks for the PR, this is definitively a good idea.

We should make this configurable, similar to how we treat `__toString`. Default can be `true` (enabled).

Btw. do you have any good examples of libraries or packages that make use of `__debugInfo`?

**Comment by mahagr** [comment]
Well, `__toString()` is really not configurable as the options are almost never being passed to the constructor of `Serializer`.

If we make this configurable, I would also add some other methods to the list, such as: `jsonSerialize()` and `toArray()`.. Or even better: maybe allow user to pass a list of serialize methods?

Grav 1.7 uses some `__debugInfo()` and I'm adding more whenever I find dumped data to be too complicated. We often have container or collection/directory references in our classes, not to mention some calculated caching information which makes no sense to be dumped unless I'm debugging a bug in that logic.

**Comment by itsgoingd** [comment]
True, this needs to be supported in the log api. I though we already allow passing serializer options in log message context. Eg. if I need some data that is not exposed in `__debugInfo` I want to be able to call:

```php
clock()->log($whatever, [ 'debugInfo' => false ];
```

Can't think of any other places where we realistically need non-default serializer options (since the defaults are also configurable).

I'm down to support more common serialization methods, I've already wanted to support `toArray()` in some form for Eloquent models.

User-configurable serialization methods - maybe if it can be done cleanly while keeping the simple configuration for the common ones (as in the example above). But I think it's reasonable to expect users to choose one of the common methods to implement.

I was interested in your use-case becasue I don't think I've ever seen this used anywhere, seems like a pretty cool PHP feature. :)

**Comment by mahagr** [comment]
Thanks for merging this!

**Pull request merged**
