### PR TITLE
Fix Symfony 6 compatibility

### PR DESCRIPTION
**Pull request by BafS**
Fix https://github.com/itsgoingd/clockwork/pull/545

### CODE REVIEW

**Comment by itsgoingd** [comment]
This will have to wait for Clockwork 6, since we don't want to drop support for previous PHP versions in a patch release.

Btw, is this backwards compatible with the previous Symfony releases?

**Comment by mahagr** [comment]
I think that the same works here as with the logger interface: just provide two different classes for the integration.

**Comment by BafS** [comment]
Yes it would be backward compatible with previous Symfony releases.

Okay if you don't want to drop PHP versions, but it's not a BC or incompatible with semver.

As @mahagr proposes, we can workaround this and do an "if" PHP 5.6

**Comment by itsgoingd** [comment]
Since this is backwards compatible with previous Symfony versions, I think it's fine to merge this to master now and release it later in Clockwork 6. So people who need this can use master for now. Can we remove the composer.json change for now, tho?

**Comment by BafS** [comment]
Okay, I changed it back to 5.6 but FYI you have 0% installation on PHP 5 (https://packagist.org/packages/itsgoingd/clockwork/php-stats#5), why not dropping it in a minor release?

**Comment by itsgoingd** [comment]
Thanks! I think it's a good policy to have so we don't cut-off old PHP users from bug fixes and future updates because of a minor change. Once we decide to up the required version we will embrace it in the whole codebase. The stats look good though, we might go straight for 7.4 as target in Clockwork 6.

**Pull request merged**
