### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by alexbegoon**
https://github.com/itsgoingd/clockwork/issues/450

### CODE REVIEW

**Comment by itsgoingd** [comment]
Thanks!

**Comment by mahagr** [comment]
PS: If you had phpstan tests and proper docblocks, this issue would have been caught. :)

**Comment by alexbegoon** [comment]
> PS: If you had phpstan tests and proper docblocks, this issue would have been caught. :)

Agree, but everything comes at a cost :slightly_smiling_face:

**Comment by mahagr** [comment]
Yup, I've been updating a larger project to use phpstan for over a year now and I still have tons of errors left. But I have to say that it is really good for improving the code quality as you find out how not to write the code. :)

**Pull request merged**
