### PR TITLE
fix resolveSlackChannelSpecific for slack notification v3

### PR DESCRIPTION
**Pull request by maximepvrt**
solve #643

### CODE REVIEW

**Comment by itsgoingd** [comment]
Hey, thanks for the PR! I'm not sure if it's better to log the JSON encoded blocks or the fallback text. Do you have a screenshot how this implementation look like in the Clockwork app?

**Comment by maximepvrt** [comment]
Capture d’écran 2023-08-01 à 23 26 16

Content attribut is not showable on Clockwork app :/

**Comment by itsgoingd** [comment]
Content should show when you click on the "search" icon (it doesn't make much sense, I know :D).

**Comment by maximepvrt** [comment]
Capture d’écran 2023-08-02 à 00 05 57
this js error is thrown if the object is not a string array. I what I see the preview is only for mail, the content preview is embedded in an iframe

**Comment by maximepvrt** [comment]
https://app.slack.com/block-kit-builder/ this route can preview the slack json content https://github.com/laravel/slack-notification-channel/blob/3.x/src/Slack/SlackMessage.php#L282 create a button to this url or embed this page can be cool (only for block-kit slack notification)

**Comment by itsgoingd** [comment]
Ah, my bad, actually formatting the data like this should show the message in the Clockwork UI:

```php
$data = [
	'from' => $message->toArray()['username'] ?? null,
	'to' => $message->toArray()['channel'] ?? null,
	'data' => [
		'content' => json_encode($message->toArray()['blocks'] ?? $message->toArray()['attachments'])
	]
];
```

Yeah, we can add a preview button in a future release.

**Comment by maximepvrt** [comment]
Perfect, it works ! PR updated ;)

Capture d’écran 2023-08-02 à 10 39 32

Would it be a good idea to open an issue for changing the search icon of the email notification preview? What do you think?

**Comment by maximepvrt** [comment]
🙏 @itsgoingd

**Comment by itsgoingd** [comment]
Thanks! I will clean up the UI for the next major release soon.

**Pull request merged**
