### PR TITLE
Doctrine DataSource rework

### PR DESCRIPTION
**Pull request by sperrichon**
Changes: 

* Added a DBAL DataSource that only need a DBAL Connection, in case you're not using the ORM
* Made the Doctrine DataSource extend the DBAL DataSource since only the source of the connection differs
* Made possible to keep the current associated SQLLogger on the Connection, defaults to the actual behavior
* If you pass the Timeline, it will also collect query times via events

I've been doing this as a part of building an API with Slim, DBAL, Monolog, Clockwork, and PSR-7 in mind. (I also intend to make a PSR-7 Request DataSource.)

### CODE REVIEW

**Comment by itsgoingd** [comment]
Looks great, thanks! Not a Doctrine user myself, so any help with this part of the code is much appreciated.

Is there any reason why you would want to replace the logger if one is already set? I'd prefer for dropping that option and simply auto-detecting existing logger and always using logger chain in that case.

PSR-7 data source sound like a great idea, looking forward to that PR!

**Comment by sperrichon** [comment]
Currently the Doctrine DataSource gets its connection from the Entity Manager and then sets itself as the logger, thus replacing the current logger if there was any. The only reason I kept this behavior to be compatible with the current version. 
I don't see any problem removing the option tho.

**Comment by itsgoingd** [comment]
Let's drop it and make it a default please. I think this is better behavior, and will be released in a next major version, so slight behavior change is not a major concern.

**Comment by sperrichon** [comment]
Great then, adjusted the commits.

**Comment by itsgoingd** [comment]
Thanks!

**Pull request merged**
