### PR TITLE
Update TwigDataSource to using engine Twig

### PR DESCRIPTION
**Pull request by ericktucto**
Actually, TwigDataSource dont using the Twig's class. I updated TwigDataSource to use on Clockwork ([click to see Twig's class](https://github.com/twigphp/Twig/blob/3.x/src/Environment.php#L41))

### CODE REVIEW

**Comment by itsgoingd** [comment]
I think this breaks compatibility w/ older Twig versions, I will wait with merging for the next major release.

**Comment by ericktucto** [comment]
But the current DataSource for Twig doesn't support the new Twig namespace, do I modify my PR to accept both?  Or will this new DataSource be implemented in the new version of Clockwork?

**Comment by itsgoingd** [comment]
Hm, I guess it can be made backwards-compatible by removing the typehint in the constructor and checking whether one of the profiler classes exists. That might be a good solution.

**Comment by itsgoingd** [comment]
Implemented this in a backwards-compatible way in `dev-master`. We should now support all Twig versions. Thanks for the PR!

**Pull request closed without merging**
